### ISSUE TITLE
[US] - Dashboard for sorting a list of roads

### ISSUE THREAD

**Issue by mikk5829** [Software-Engineering-2-group-E/LiRA-Map#10]
**As a**
LiRA-Map user with a list of roads I'm interrested in
**I want**
a dashboard where I get my list of roads sorted by their condition
**so that**
I can get a better Idea on the roads conditions

@RasserAlt suggestion

**Comment by Zarkino** [comment]
Have a look at [https://github.com/Software-Engineering-2-group-E/LiRA-Map/issues/89](url)
