### ISSUE TITLE
[US] - Add gray layer for OpenStreetMap

### ISSUE THREAD

**Issue by Zarkino** [Software-Engineering-2-group-E/LiRA-Map#102]
**As a**
LiRA-Map user
**I want**
A gray layer on the OpenStreetMap
**so that**
it is easier to see the visualizations.

**Comment by Zarkino** [comment]
Overlaps with task from [Issue #82](https://github.com/Software-Engineering-2-group-E/LiRA-Map/issues/82)

**Comment by afskylia** [comment]
Duplicate
