### ISSUE TITLE
[US] - Make text in Dark Mode more readable

### ISSUE THREAD

**Issue by Zarkino** [Software-Engineering-2-group-E/LiRA-Map#117]
**As a**
LiRA Map user
**I want**
Text to be more readable (The dark blue text on the signup/login links or on the selected page on the navigation bar)
**so that**
I can read all text easily.

Examples:
![Login](https://user-images.githubusercontent.com/31597902/201362497-e4a3b18c-e7c2-4524-bb84-22561826c9ba.png)
![Navigation Bar](https://user-images.githubusercontent.com/31597902/201362500-4054d628-c048-4790-897e-3dffcd8ec1b9.png)

**Comment by jonasmittun** [comment]
I intend to also fix some of the darkmode bugs that are present, like the trip data in darkmode.

**Comment by jonasmittun** [comment]
I'm having difficulties changing the button themes using overrides as shown in the following:
https://mui.com/material-ui/customization/theme-components/#global-style-overrides

Dark theme plain texts now fixed to be more visible and the meta data window is also fixed.
