### ISSUE TITLE
Hashed and salted sign up

### ISSUE THREAD

**Issue by Boombalar** [Software-Engineering-2-group-E/LiRA-Map#32]
**As a**
Lira-map user
**I want**
to be able to sign up/create a user
**so that**
I can login with my user and get access to the webpage.

**Comment by mikk5829** [comment]
I think we should have the following information:

- [ ] First name (for personalisation)
- [ ] Last name (for personalisation)
- [ ] E-mail
- [ ] Password (at least 12 characters long)

**Comment by mikk5829** [comment]
@Boombalar Hvis den er 34 story points så skal det ikke implementeres!

**Comment by Boombalar** [comment]
Won't do, Knex does not work
