### ISSUE TITLE
[BUG] - Include database login information securely

### ISSUE THREAD

**Issue by afskylia** [Software-Engineering-2-group-E/LiRA-Map#36]
* loginoplysninger skal gemmes et sted (som ikke bliver pushet, eller brug encrypted secrecy)
* servernest skal køre for at kortet bliver vist

**Comment by mikk5829** [comment]
@afskylia missing story points

**Comment by afskylia** [comment]
@mikk5829 du har fået æren af at lave denne!

**Comment by afskylia** [comment]
Nevermind, det var jo bare at sætte .env-filer op - forstod ikke helt opgaven, jeg oprettede den bare hæhæ
