### ISSUE TITLE
Investigate energy usage

### ISSUE THREAD

**Issue by afskylia** [Software-Engineering-2-group-E/LiRA-Map#43]
We need to start researching new kinds of data to visualize in LiRA Map, e.g. energy usage - which variables are necessary to compute energy usage, and how do we get access to those and start calculating energy usage.

**Comment by markusbrammer** [comment]
See section 3.1.2 and chapter 5 in Sergi Doce Planas' thesis. 
The data can be found in the `Measurements` table for the `public` schema. Decoding the cryptic `MeasurementTypes` [here](https://docs.google.com/spreadsheets/d/17HTsVYUhFQYOamQyFi0uDZHBRL6TYKJxvLtX9YmBgY4/edit?usp=sharing).
