### ISSUE TITLE
[US] - app to use production build

### ISSUE THREAD

**Issue by mikk5829** [Software-Engineering-2-group-E/LiRA-Map#50]
**As a**
Lira map user
**I want**
The app to use production build
**so that**
I get a fast experience

**Comment by afskylia** [comment]
@mikk5829 tror vi skal slappe lidt af med at lave user stories til alle tasks xD Ekkart sagde også at vores user stories var for tekniske, vi skal kun lave user stories fra end-userens perspektiv, og brugeren ved intet om production builds osv.

Tænker vi kan nøjes med kun at lave "[US]" tasks ved nogle meget konkrete end-user-relevante tasks

**Comment by mikk5829** [comment]
@afskylia task tsk :PP
